"""Chunk -> question-answer pairs, generated by an LLM on Groq.

Each chunk yields ``generate.questions_per_chunk`` answerable pairs. A seeded
``generate.unanswerable_ratio`` share of chunks also yields one plausible
question the passage does *not* answer, paired with a fixed abstention answer.
"""

from __future__ import annotations

import hashlib
import json
import math
import random
import re
import time
from pathlib import Path
from typing import Any, Callable

from langchain_core.documents import Document

from src.config import CONFIG, Config, resolve_path
from src.llm import FatalLLMError, LLMCallError, Usage, invoke_json

ProgressCallback = Callable[[int, int, str], None]

# Bump when a prompt changes, so old checkpoints are not reused for a new prompt.
PROMPT_VERSION = "gen-v3"
# Earlier versions whose COMPLETE chunks may be kept by --refill (see generate_from_chunks),
# with the config keys each version predates (left out when recomputing its fingerprint).
LEGACY_PROMPT_VERSIONS: dict[str, tuple[str, ...]] = {"gen-v2": ("source_reference",)}

TYPE_GUIDE = {
    "factual": 'asks for a specific fact the passage states: a number, finding, population, date or '
               'recommendation (e.g. "What minimum daily fibre intake does WHO recommend for adults?")',
    "definitional": 'asks what a term, concept, classification or threshold means as the passage defines it '
                    '(e.g. "How does WHO define moderate wasting in children?")',
    "procedural": 'asks how something is done or should be done: steps, methods, conditions or criteria '
                  '(e.g. "How should health workers assess a child presenting with suspected obesity?")',
}

_GENERIC_QUESTION = re.compile(
    r"\b(this|the)\s+(passage|section|text|excerpt|document|chunk)\b.*\b(about|discuss|describe|say|cover|mention)",
    re.IGNORECASE,
)
# "the passage" cannot stand alone once the passage is gone; it is rewritten to name the source.
_REFERS_TO_SOURCE = re.compile(r"\b(the|this|above)\s+(passage|text|excerpt|section|chunk|paragraph)\b",
                               re.IGNORECASE)


def normalize_source_references(text: str, cfg: Config = CONFIG) -> str:
    """Rewrite "the passage" / "this section" to ``generate.source_reference``.

    Why rewrite instead of drop: the model often phrases a good, grounded
    question as "According to the passage, ...". Dropping those discarded a
    third of the pairs in testing. The rewrite is faithful, because the passage
    is part of that guideline, and it keeps the question meaningful without
    the passage.
    """
    ref = cfg.generate.source_reference

    def replace(match: re.Match) -> str:
        return ref[:1].upper() + ref[1:] if match.group(0)[:1].isupper() else ref

    return _REFERS_TO_SOURCE.sub(replace, text)


def system_prompt(cfg: Config = CONFIG) -> str:
    return (
        f"You are {cfg.domain.system_role}. You write question-answer pairs used to "
        "fine-tune a language model. Accuracy matters more than anything else: never state "
        "anything the source passage does not support. You reply with valid JSON only."
    )


def generation_prompt(chunk_text: str, cfg: Config = CONFIG, source: str = "", page: Any = "") -> str:
    """User prompt for answerable pairs. Every rule here maps to a spec requirement."""
    n = cfg.generate.questions_per_chunk
    types = cfg.generate.question_types
    type_lines = "\n".join(f'   - "{t}": {TYPE_GUIDE.get(t, t)}' for t in types)
    where = f" (from {source}, page {page})" if source else ""
    return f"""Write exactly {n} question-answer pairs based on the passage below{where}.

Rules:
1. Every answer must come ONLY from the passage. Do not add facts, numbers, advice or context from outside knowledge, even if you know them to be true.
2. Each answer is 1-3 complete sentences: factual, precise and self-contained (it makes sense without seeing the question).
3. Each question must test knowledge of this particular content and be answerable from the passage alone. Write it as a standalone question a health professional could ask without seeing the passage: name the subject explicitly (the recommendation, population or study it concerns). Never write "the passage", "the text", "this section" or "the document"; if you must refer to the source, write "{cfg.generate.source_reference}".
4. Never ask generic questions such as "What is this passage about?" or "What does this section discuss?".
5. Question types. Cover different types where the passage supports them, and tag each pair with the type it truly is:
{type_lines}
   Never force a type: if the passage has no procedure, do not label a factual question "procedural".
6. Do not copy citation markers such as "(22)" or "[4]" into questions or answers.
7. If the passage has no substantive {cfg.domain.name} content (only names, affiliations, copyright text, a contents list or a bibliography), return [].

Output ONLY a JSON array, with no prose before or after it:
[{{"question": "...", "answer": "...", "question_type": "{types[0]}"}}]

Passage:
\"\"\"
{chunk_text}
\"\"\""""


def unanswerable_prompt(chunk_text: str, cfg: Config = CONFIG) -> str:
    return f"""Read the passage below. Write ONE question that a health professional might plausibly ask about the same topic, but which the passage does NOT answer.

Requirements:
- Stay on the passage's topic, so the question sounds natural for {cfg.domain.name}.
- The passage must contain no information that answers it, not even partially. Good options: a dosage, time frame, population, side effect, cost or comparison that the passage never mentions.
- Do not refer to "the passage" or "the text", and do not ask about the document itself (authors, dates, page numbers).

Output ONLY a JSON object, with no prose before or after it:
{{"question": "..."}}

Passage:
\"\"\"
{chunk_text}
\"\"\""""


# ---------------------------------------------------------------------------
# Single-chunk generation
# ---------------------------------------------------------------------------
def _pair_id(chunk_id: str, question: str) -> str:
    return hashlib.sha1(f"{chunk_id}|{question.strip().lower()}".encode("utf-8")).hexdigest()[:12]


def filter_pairs(raw: Any, cfg: Config = CONFIG) -> list[dict[str, Any]]:
    """Keep only well-formed pairs from parsed model output.

    Well-formed: a dict with a question over ``min_question_chars`` and an
    answer over ``min_answer_chars``, not a generic "what is this about"
    question, not the abstention string, and not a repeat within the chunk.
    References to "the passage" are rewritten to name the source (see
    normalize_source_references); the generic check runs first, so "What is
    this passage about?" is still dropped rather than rewritten.
    Unknown question types are kept but tagged "other" so the distribution
    chart shows the model drifting rather than hiding it.
    """
    if not isinstance(raw, list):
        return []
    allowed = {t.lower() for t in cfg.generate.question_types}
    abstain = cfg.generate.abstention_answer.strip().lower()
    seen: set[str] = set()
    pairs: list[dict[str, Any]] = []
    for item in raw:
        if not isinstance(item, dict):
            continue
        q = item.get("question")
        a = item.get("answer")
        if not isinstance(q, str) or not isinstance(a, str):
            continue
        q, a = " ".join(q.split()), " ".join(a.split())
        if len(q) <= cfg.generate.min_question_chars or len(a) <= cfg.generate.min_answer_chars:
            continue
        if _GENERIC_QUESTION.search(q) or a.lower() == abstain:
            continue
        q, a = normalize_source_references(q, cfg), normalize_source_references(a, cfg)
        if q.lower() in seen:
            continue
        seen.add(q.lower())
        qtype = str(item.get("question_type", "")).strip().lower()
        pairs.append({"question": q, "answer": a, "question_type": qtype if qtype in allowed else "other"})
    return pairs[: cfg.generate.questions_per_chunk]


def generate_qa_pairs(
    chunk_text: str,
    cfg: Config = CONFIG,
    *,
    source: str = "",
    page: Any = "",
    usage: Usage | None = None,
    api_key: str | None = None,
    errors: list[str] | None = None,
    raw_counts: list[int] | None = None,
) -> list[dict[str, Any]]:
    """Generate answerable pairs for one chunk; ``[]`` on failure (never raises, except fatal).

    Temperature 0.4: higher (0.7+) gives more creative questions but more
    hallucination; lower (0.1) gives repetitive phrasing. 0.4 balances variety
    against faithfulness. Failures are appended to ``errors`` and the number of
    pairs the model returned (before filtering) to ``raw_counts``, when given.
    """
    usage = usage if usage is not None else Usage()
    try:
        raw = invoke_json(
            model_id=cfg.model.id,
            temperature=cfg.model.generation_temperature,
            system=system_prompt(cfg),
            user=generation_prompt(chunk_text, cfg, source, page),
            expect=list,
            expected_output_tokens=100 * cfg.generate.questions_per_chunk + 200,
            max_tokens=cfg.model.generation_max_tokens,
            usage=usage,
            cfg=cfg,
            api_key=api_key,
        )
    except FatalLLMError:
        raise
    except LLMCallError as exc:
        if errors is not None:
            errors.append(str(exc))
        return []
    if raw_counts is not None:
        raw_counts.append(len(raw) if isinstance(raw, list) else 0)
    return filter_pairs(raw, cfg)


def generate_unanswerable(
    chunk_text: str,
    cfg: Config = CONFIG,
    *,
    usage: Usage | None = None,
    api_key: str | None = None,
    errors: list[str] | None = None,
) -> dict[str, Any] | None:
    """One plausible, on-topic question the passage cannot answer, or None on failure.

    Why: a model trained only on answerable questions learns that every
    question has an answer, and hallucinates when it does not know. These
    examples teach it to abstain. The answer is the fixed abstention string,
    set here in code rather than trusted to the model.
    """
    usage = usage if usage is not None else Usage()
    try:
        raw = invoke_json(
            model_id=cfg.model.id,
            temperature=cfg.model.generation_temperature,
            system=system_prompt(cfg),
            user=unanswerable_prompt(chunk_text, cfg),
            expect=dict,
            expected_output_tokens=250,
            max_tokens=cfg.model.generation_max_tokens,
            usage=usage,
            cfg=cfg,
            api_key=api_key,
        )
    except FatalLLMError:
        raise
    except LLMCallError as exc:
        if errors is not None:
            errors.append(str(exc))
        return None
    question = raw.get("question") if isinstance(raw, dict) else None
    if not isinstance(question, str):
        return None
    question = " ".join(question.split())
    if len(question) <= cfg.generate.min_question_chars or _GENERIC_QUESTION.search(question):
        return None
    question = normalize_source_references(question, cfg)
    return {
        "question": question,
        "answer": cfg.generate.abstention_answer,
        "question_type": "unanswerable",
        "answerable": False,
    }


# ---------------------------------------------------------------------------
# Checkpointing
# ---------------------------------------------------------------------------
def run_fingerprint(chunks: list[Document], cfg: Config, kind: str, prompt_version: str,
                    omit_generate_keys: tuple[str, ...] = ()) -> str:
    """Hash of everything that determines the generation stage's output.

    Why: resuming must never mix results from a different PDF set, prompt or
    setting into the current run. A checkpoint is reused only when this matches.
    ``omit_generate_keys`` recomputes the fingerprint of an older prompt
    version that predates those config keys (used by --refill).
    """
    h = hashlib.sha256()
    generate_settings = {k: v for k, v in cfg.generate.to_dict().items() if k not in omit_generate_keys}
    settings = {
        "kind": kind,
        "prompt": prompt_version,
        "model": [cfg.model.id, cfg.model.generation_temperature, cfg.model.reasoning_effort],
        "domain": cfg.domain.to_dict(),
        "generate": generate_settings,
        "seed": cfg.run.seed,
    }
    h.update(json.dumps(settings, sort_keys=True).encode("utf-8"))
    for c in chunks:
        h.update(c.metadata.get("chunk_id", "").encode("utf-8"))
        h.update(hashlib.sha1(c.page_content.encode("utf-8")).digest())
    return h.hexdigest()[:20]


def load_checkpoint(path: Path, fingerprint: str) -> dict[str, dict[str, Any]]:
    """Records from a checkpoint file that belong to this exact run, keyed by id."""
    records: dict[str, dict[str, Any]] = {}
    if not path.is_file():
        return records
    with open(path, "r", encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            try:
                rec = json.loads(line)
            except json.JSONDecodeError:
                continue  # a line cut off by a crash mid-write
            if rec.get("fingerprint") == fingerprint:
                records[rec["key"]] = rec
    return records


def append_checkpoint(path: Path, records: list[dict[str, Any]]) -> None:
    if not records:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "a", encoding="utf-8") as fh:
        for rec in records:
            fh.write(json.dumps(rec, ensure_ascii=False) + "\n")
        fh.flush()
    records.clear()


def unanswerable_chunk_ids(chunks: list[Document], cfg: Config = CONFIG) -> set[str]:
    """Seeded, reproducible choice of which chunks also get an unanswerable question.

    ceil() so that even a 5-chunk smoke test exercises the unanswerable path.
    """
    ratio = cfg.generate.unanswerable_ratio
    if ratio <= 0 or not chunks:
        return set()
    k = min(len(chunks), math.ceil(len(chunks) * ratio))
    ids = [c.metadata["chunk_id"] for c in chunks]
    return set(random.Random(cfg.run.seed).sample(ids, k))


# ---------------------------------------------------------------------------
# Batch generation
# ---------------------------------------------------------------------------
def generate_from_chunks(
    chunks: list[Document],
    cfg: Config = CONFIG,
    progress_callback: ProgressCallback | None = None,
    *,
    cache_dir: str | Path | None = None,
    resume: bool = False,
    refill: bool = False,
    api_key: str | None = None,
    report: dict[str, Any] | None = None,
) -> list[dict[str, Any]]:
    """Generate pairs for every chunk, with progress, pacing and checkpointing.

    ``progress_callback(current, total, stage)`` is optional: the CLI passes
    nothing, the web interface passes a function that drives a progress bar.

    Checkpoint: every ``run.checkpoint_every`` chunks (and on any exit, including
    Ctrl+C or a fatal API error) finished chunks are appended to
    ``<cache_dir>/generate_checkpoint.jsonl``. With ``resume=True``, chunks
    already completed by an identical run are skipped; failed chunks are
    retried. Without it the checkpoint is discarded and the run starts fresh.

    ``refill=True`` (implies resume) upgrades a run made with an older prompt
    version: chunks that already produced the full ``questions_per_chunk``
    pairs under a version listed in LEGACY_PROMPT_VERSIONS are kept, and every
    other chunk is regenerated with the current prompt. Each record keeps its
    ``prompt_version``, so the dataset states which prompt made each pair.

    Pacing: requests are spaced by ``model.request_delay_seconds`` and kept
    under the tokens-per-minute cap by the shared limiter in src/llm.py.

    ``report`` (optional dict) receives counts and token usage for the stats file.
    """
    cache = resolve_path(cache_dir or cfg.paths.cache_dir)
    ckpt_path = cache / "generate_checkpoint.jsonl"
    fingerprint = run_fingerprint(chunks, cfg, "generate", PROMPT_VERSION)
    resume = resume or refill
    if not resume and ckpt_path.exists():
        ckpt_path.unlink()
    done = load_checkpoint(ckpt_path, fingerprint) if resume else {}
    done = {k: r for k, r in done.items() if r.get("status") in ("ok", "empty", "filtered", "skipped")}
    pending: list[dict[str, Any]] = []
    carried = 0
    if refill:
        n = cfg.generate.questions_per_chunk
        for version, newer_keys in LEGACY_PROMPT_VERSIONS.items():
            legacy_fp = run_fingerprint(chunks, cfg, "generate", version, newer_keys)
            for key, rec in load_checkpoint(ckpt_path, legacy_fp).items():
                if key not in done and rec.get("status") == "ok" and len(rec.get("pairs", [])) >= n:
                    # Apply the current source-reference rewrite to carried-over text as well, and
                    # re-stamp under the current fingerprint so a later plain --resume finds it.
                    pairs = [{**p, "question": normalize_source_references(p["question"], cfg),
                              "answer": normalize_source_references(p["answer"], cfg), "prompt_version": version}
                             for p in rec["pairs"]]
                    unans = rec.get("unanswerable")
                    if unans:
                        unans = {**unans, "question": normalize_source_references(unans["question"], cfg),
                                 "prompt_version": version}
                    done[key] = {**rec, "pairs": pairs, "unanswerable": unans,
                                 "fingerprint": fingerprint, "prompt_version": version}
                    pending.append(done[key])
                    carried += 1

    unans_ids = unanswerable_chunk_ids(chunks, cfg)
    total = len(chunks)
    usage = Usage()
    all_pairs: list[dict[str, Any]] = []
    counts = {"ok": 0, "empty": 0, "filtered": 0, "failed": 0}
    resumed = 0
    started = time.time()
    print(f"Generating Q&A with {cfg.model.id} for {total} chunks "
          f"({cfg.generate.questions_per_chunk}/chunk, {len(unans_ids)} unanswerable, prompt {PROMPT_VERSION})"
          + (f"; reusing {len(done)} finished chunks" if done else "")
          + (f" ({carried} complete chunks carried over from an older prompt)" if carried else ""))

    def pairs_from(record: dict[str, Any]) -> list[dict[str, Any]]:
        return list(record.get("pairs", [])) + ([record["unanswerable"]] if record.get("unanswerable") else [])

    try:
        for i, chunk in enumerate(chunks, start=1):
            meta = chunk.metadata
            cid = meta["chunk_id"]
            if cid in done:
                record = done[cid]
                resumed += 1
                status = "empty" if record["status"] == "skipped" else record["status"]
                counts[status] = counts.get(status, 0) + 1
                all_pairs.extend(pairs_from(record))
                if progress_callback:
                    progress_callback(i, total, "generating")
                continue

            errors: list[str] = []
            raw_counts: list[int] = []
            chunk_usage = Usage()
            pairs = generate_qa_pairs(
                chunk.page_content, cfg, source=meta["source"], page=meta["page"],
                usage=chunk_usage, api_key=api_key, errors=errors, raw_counts=raw_counts,
            )
            unans = None
            if cid in unans_ids:
                unans = generate_unanswerable(chunk.page_content, cfg, usage=chunk_usage,
                                              api_key=api_key, errors=errors)
            usage.add(chunk_usage)

            base = {
                "source": meta["source"],
                "page": meta["page"],
                "page_label": meta.get("page_label", str(meta["page"])),
                "chunk_id": cid,
                "chunk_text": chunk.page_content,
                "prompt_version": PROMPT_VERSION,
            }
            for p in pairs:
                p.update(base, answerable=True, id=_pair_id(cid, p["question"]))
            if unans:
                unans.update(base, id=_pair_id(cid, unans["question"]))

            returned = raw_counts[-1] if raw_counts else 0
            if errors and not raw_counts:
                status = "failed"
            elif pairs:
                status = "ok"
            elif returned:
                status = "filtered"  # the model wrote pairs, but none passed filter_pairs
            else:
                status = "empty"  # the model judged the chunk to have no substantive content
            counts[status] += 1
            record = {"fingerprint": fingerprint, "key": cid, "status": status, "prompt_version": PROMPT_VERSION,
                      "raw_count": returned, "pairs": pairs, "unanswerable": unans, "errors": errors[-1:],
                      "usage": chunk_usage.to_dict()}
            pending.append(record)
            all_pairs.extend(pairs_from(record))

            note = {"ok": f"{len(pairs)} pairs", "empty": "no substantive content",
                    "filtered": f"all {returned} pairs filtered out",
                    "failed": f"FAILED ({errors[-1][:80] if errors else 'unknown'})"}[status]
            extra = " +1 unanswerable" if unans else ""
            print(f"  [{i:>3}/{total}] {meta['source']} p{meta['page']}: {note}{extra}", flush=True)
            if progress_callback:
                progress_callback(i, total, "generating")
            if len(pending) >= cfg.run.checkpoint_every:
                append_checkpoint(ckpt_path, pending)
    finally:
        append_checkpoint(ckpt_path, pending)

    # Token usage for chunks restored from the checkpoint still counts toward the run.
    for record in done.values():
        usage.add(Usage.from_dict(record.get("usage")))
    answerable = sum(1 for p in all_pairs if p.get("answerable", True))
    unanswerable = len(all_pairs) - answerable
    elapsed = time.time() - started
    by_version: dict[str, int] = {}
    for p in all_pairs:
        v = p.get("prompt_version", "gen-v2")
        by_version[v] = by_version.get(v, 0) + 1
    print(f"Generation done in {elapsed:.0f}s: {answerable} pairs + {unanswerable} unanswerable "
          f"from {total} chunks; {counts['failed']} failed, {counts['empty']} with no substantive content, "
          f"{counts['filtered']} fully filtered" + (f", {resumed} reused" if resumed else "")
          + f". Tokens used: {usage.total_tokens:,} over {usage.calls} calls.")
    if report is not None:
        report.update({
            "chunks": total, "chunks_failed": counts["failed"], "chunks_empty": counts["empty"],
            "chunks_filtered": counts["filtered"], "chunks_resumed": resumed, "chunks_carried_over": carried,
            "pairs_generated": answerable, "unanswerable_generated": unanswerable,
            "pairs_by_prompt_version": by_version, "seconds": round(elapsed, 1), "usage": usage.to_dict(),
        })
    return all_pairs


if __name__ == "__main__":
    from src.ingest import chunk_documents, load_pdfs, select_chunks

    # Smoke test on five chunks only, before spending hundreds of API calls.
    docs = load_pdfs(CONFIG.paths.raw_dir)
    sample = select_chunks(chunk_documents(docs), 5)
    results = generate_from_chunks(sample, CONFIG, cache_dir=resolve_path(CONFIG.paths.cache_dir) / "smoke")
    for pair in results:
        print(f"\n[{pair['question_type']}] {pair['source']} p{pair['page']}")
        print(f"Q: {pair['question']}")
        print(f"A: {pair['answer']}")
